# 商业转载请联系作者获得授权，非商业转载请注明出处。
# For commercial use, please contact the author for authorization. For non-commercial use, please indicate the source.
# 协议(License)：署名-非商业性使用-相同方式共享 4.0 国际 (CC BY-NC-SA 4.0)
# 作者(Author)：lhllhx
# 链接(URL)：https://blog.3628688.xyz/index.php/2021/02/03/%E5%88%A9%E7%94%A8github-action%E5%AE%9E%E7%8E%B0pt%E8%87%AA%E5%8A%A8%E7%AD%BE%E5%88%B0%E5%92%8C%E6%95%B0%E6%8D%AE%E7%BB%9F%E8%AE%A1/
# 来源(Source)：lhllhx Blog

tasks:
  #自动签到
  sign_in:
    auto_sign_in:
      user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.111 Safari/537.36'
      max_workers: 1
      get_messages: no #设为no跳过获取未读信息。默认no
      get_details: yes #设为no跳过获取统计。默认yes      
      aipocr:  #baidu ocr参数
        app_id: '23818147'
        api_key: 't3GnGoIonWfje00xxSpnEMPu'
        secret_key: 'hoXKTzoNpi4PgGQDD9ALpZTNb42DMcK1'
      sites:
      #以下为具体站点设置 
      #https://github.com/lhllhx/flexget_qbittorrent_mod/tree/master/ptsites 下存在需要的站点 只需配置相应的 主域名: cookie 
        1ptba: xxxxxxxx
      #部分cookie过期太快，而改用模拟登陆的站点，如以下站点 无此站点的请删除，请删除
        filelist:
          login:
            username: xxxxxxxx
            password: xxxxxxxx
        hdpost:
          login:
            usernameOrEmail: xxxxxxxx
            password: xxxxxxxx
        ourbits:
          # ourbits 在同时配置了cookie 和 login 时，会忽略login 使用cookie签到 
          cookie: xxxxxxxx
          login:
            username: xxxxxxxx
            password: xxxxxxxx
        skyey2:
          login:
            username: xxxxxxxx
            password: xxxxxxxx
        m-team:
          login:
            username: 'xxxxxxxx'
            password: 'xxxxxxxx'
            #二次验证, 扫描二维码得到文本 otpauth://totp/*****:****?secret=[secret_key]&issuer=***** (只取[secret_key]部分)
            secret_key: <secret_key>
        #u2特殊设置 无此站点的请删除
        dmhy:
          username: <username>
          cookie: 'xxxxxxx'
          # 五个字符以上签到留言
          comment: <comment>
          ocr_config:
            # 重试次数
            retry: 3
            # 最低识别字符数
            char_count: 3
            # 最低匹配分数
            score: 50     
    accept_all: yes
    seen:
      fields:
        - title
    notify:
      task:
        always_send: true
        message: |+
          {%- if task.accepted -%}
          {%- for group in task.accepted|groupby('task') -%}
          FlexGet has just signed in {{ group.list|length }} sites for task {{ group.grouper }}:
          {% for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} {{ entry.result }}
          {%- if entry.messages|d('') %}
          Messages: {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
          {%- if task.failed %}
          {% for group in task.failed|groupby('task') %}
          The following sites have failed for task {{ group.grouper }}:
          {% for entry in group.list %}
          {{ loop.index }}: {{ entry.title }} Reason: {{ entry.reason|d('unknown') }}
          {%- if entry.messages|d('') %}
          Messages: {{ entry.messages }}
          {% endif %}
          {%- endfor -%}
          {%- endfor -%}
          {%- endif -%}
{1}# 此行，请整行删除
        via: #推送渠道选择，选择你需要的推送渠道 将不需要的删掉
          - wecom:  #微信,填写上面步骤获取到的信息
              corp_id: 'wwe5aa4d328933b978'
              corp_secret: 'm7p5NYJOGKrDyHhiE6eVxFvuW3RRbq_tcaxlBitmW-U'
              agent_id: '1000004'
              to_user: '@all'
              image: 'details_report.png' 
#          - telegram_mod: #tg
#              bot_token: ''
#              image: 'details_report.png'
#              recipients:
#                - username: '' #注意这里是用户名，不是昵称
